language: python

install:
  - deactivate
  - curl -L https://bootstrap.saltstack.com | sudo sh -s
  - sudo salt-call state.highstate --local --config-dir=./salt

script:
    - tox

after_success:
  - coveralls
