language: python

install:
  - deactivate
  - curl -L https://bootstrap.saltstack.com | sudo sh -s
  - sudo salt-call state.highstate --local  --file-root salt/roots/salt

script:
    - tox

after_success:
  - coveralls
