sudo: false

services:
  - docker

python:
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'

before_install:
  - docker build --tag nltk .
  - docker run --detach --name nltk nltk

env: TOXENV=py-travis

script: docker exec nltk tox -e ${TOXENV} tox.ini -vv
