language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r pip-req.txt
  - python -c "import nltk; nltk.download('all')"
# command to run tests
script:
  - python nltk/test/runtests.py
