language: python
# command to install dependencies
install:
  - curl -L https://bootstrap.saltstack.com | sudo sh -s
  - salt-call state.highstate --local --config-dir=./salt
# command to run tests
script: tox
after_success:
  - coveralls
