language: python
# command to install dependencies
install:
  - sudo apt-get install python-software-properties -y
  - sudo add-apt-repository ppa:saltstack/salt
  - sudo apt-get install salt-minion
  - salt-call state.highstate --local --config-dir=./salt
# command to run tests
script: tox
after_success:
  - coveralls
